# template/.pre-commit-config.yaml
repos:
  - repo: https://github.com/astral-sh/uv-pre-commit
    rev: 0.6.0
    hooks:
      - id: pip-compile
        args: [requirements.in, -o, requirements.txt]
  - repo: https://github.com/commitizen-tools/commitizen
    rev: v4.2.1
    hooks:
      - id: commitizen-branch
        stages: [pre-push]
        # This only checks if commits follow the conventional commits format
        # without doing any version bumping

  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v5.0.0
    hooks:
      - id: trailing-whitespace
      - id: end-of-file-fixer
      - id: check-yaml
      - id: check-toml
      - id: check-added-large-files
        args: ['--maxkb=50000']  # 50MB limit (GitHub's max file size)
      - id: debug-statements
      - id: check-case-conflict
      - id: check-merge-conflict

  - repo: https://github.com/charliermarsh/ruff-pre-commit
    rev: v0.9.6
    hooks:
      - id: ruff
        args: [--fix]
      - id: ruff-format
        exclude: ^tests/

  - repo: https://github.com/pre-commit/mirrors-mypy
    rev: v1.15.0
    hooks:
      - id: mypy
        # Because pre-commit runs mypy from an isolated virtualenv
        # add the typed dependencies to allow analysis
        exclude: ^tests/
        args: ["--config-file=pyproject.toml"]
